/********************************************************************************************************************
 * \file MULTICAN.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * Created on: 27 jul. 2022
 * Author: uif23585
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "MULTICAN.h"
#include "Bsp.h"

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
AppMulticanType   g_multican;                               /* Global MULTICAN configuration and control structure   */
AppLedType        g_led;                                    /* Global LED configuration and control structure        */
uint8             profile = 0;

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/* Macro to define Interrupt Service Routine.
 * This macro:
 * - defines linker section as .intvec_tc<vector number>_<interrupt priority>.
 * - defines compiler specific attribute for the interrupt functions.
 * - defines the Interrupt service routine as ISR function.
 *
 * IFX_INTERRUPT(isr, vectabNum, priority)
 *  - isr: Name of the ISR function.
 *  - vectabNum: Vector table number.
 *  - priority: Interrupt priority. Refer Usage of Interrupt Macro for more details.
 */
IFX_INTERRUPT(canIsrTxHandler, 0, ISR_PRIORITY_CAN_TX);
IFX_INTERRUPT(canIsrRxHandler, 0, ISR_PRIORITY_CAN_RX);

/* Interrupt Service Routine (ISR) called once the TX interrupt has been generated.
 * Turns on the LED1 to indicate successful CAN message transmission.
 */
void canIsrTxHandler(void)
{
    /* Just to indicate that the CAN message has been transmitted by turning on LED1 */
    IfxPort_setPinLow(g_led.led1.port, g_led.led1.pinIndex);
}

/* Interrupt Service Routine (ISR) called once the RX interrupt has been generated.
 * Compares the content of the received CAN message with the content of the transmitted CAN message
 * and in case of success, turns on the LED2 to indicate successful CAN message reception.
 */
void canIsrRxHandler(void)
{
    IfxMultican_Status readStatus;
    uint32 messageID = 0x7FF;
    uint32 dataHigh  = 0;
    uint32 dataLow   = 0;
    uint64 data      = 0;
    uint8  sendData  = 0;
    static sint8  direction = 1;

    /* Read the received CAN message and store the status of the operation */
    readStatus = IfxMultican_Can_MsgObj_readMessage(&g_multican.canDstMsgObj, &g_multican.rxMsg);

    /* If no new data has been received, report an error */
    if( !( readStatus & IfxMultican_Status_newData ) )
    {
        while(1)
        {
        }
    }

    /* If new data has been received but with one message lost, report an error */
    if( readStatus == IfxMultican_Status_newDataButOneLost )
    {
        while(1)
        {
        }
    }

    /* Finally, check if the received data matches with the transmitted one */
    if((profile > First_Profile) && (profile < Last_Profile))
    {
        switch(profile)
        {
            case BCM:
                if( g_multican.rxMsg.id == 0x111 )
                {
                    sendData    = 1;
                    messageID   = 0x222;
                }
                break;
            case DCU_1:
                if( g_multican.rxMsg.id == 0x222 )
                {
                    sendData    = 1;
                    messageID   = 0x333;
                }
                break;
            case DCU_2:
                if( g_multican.rxMsg.id == 0x333 )
                {
                    sendData    = 1;
                    messageID   = 0x444;
                }
                break;
            case DCU_3:
                if( g_multican.rxMsg.id == 0x444 )
                {
                    sendData    = 1;
                    messageID   = 0x555;
                }
                break;
            case DCU_4:
                if( g_multican.rxMsg.id == 0x555 )
                {
                    sendData    = 1;
                    messageID   = 0x666;
                }
                break;
            default: break;

        }

        if(sendData == 1)
        {
            sendData = 0;

            IfxPort_togglePin(LED2);

            // Join data
            data = (((uint64)g_multican.rxMsg.data[1]) << 32) + ((uint64)g_multican.rxMsg.data[0]);

            // Detect limits
            if((data == 0x1100000000000000) && (direction == 1))
            {
                direction = -1;
            }
            else if((data == 0x0000000000000011) && (direction == -1))
            {
                direction = 1;
            }
            else
            {

            }

            // Shift data
            if(direction == 1)
            {
                data = data << 8;
            }
            else{
                data = data >> 8;
            }

            // Prepare data
            dataLow     = (uint32)(data);
            dataHigh    = (uint32)(data >> 32);

            /* Initialization of the TX message */
            IfxMultican_Message_init(&g_multican.txMsg,
                                     messageID,
                                     dataLow,
                                     dataHigh,
                                     g_multican.canMsgObjConfig.control.messageLen);

            while( IfxMultican_Status_notSentBusy == IfxMultican_Can_MsgObj_sendMessage(&g_multican.canSrcMsgObj, &g_multican.txMsg) )
            {
            }
        }


    }
}

/* Function to initialize MULTICAN module, nodes and message objects related for this application use case */
void initMultican(void)
{
    /* ==========================================================================================
     * CAN module configuration and initialization:
     * ==========================================================================================
     *  - load default CAN module configuration into configuration structure
     *
     *  - define the interrupt priority for both interrupt node pointers used in the example
     *
     *  - initialize CAN module with the modified configuration
     * ==========================================================================================
     */
    IfxMultican_Can_initModuleConfig(&g_multican.canConfig, &MODULE_CAN);

    g_multican.canConfig.nodePointer[TX_INTERRUPT_SRC_ID].priority = ISR_PRIORITY_CAN_TX;
    g_multican.canConfig.nodePointer[TX_INTERRUPT_SRC_ID].typeOfService  = IfxSrc_Tos_cpu0;
    g_multican.canConfig.nodePointer[RX_INTERRUPT_SRC_ID].priority = ISR_PRIORITY_CAN_RX;
    g_multican.canConfig.nodePointer[RX_INTERRUPT_SRC_ID].typeOfService  = IfxSrc_Tos_cpu0;

    IfxMultican_Can_initModule(&g_multican.can, &g_multican.canConfig);

    /* ==========================================================================================
     * Source CAN node configuration and initialization:
     * ==========================================================================================
     *  - load default CAN node configuration into configuration structure
     *
     *  - set source CAN node
     *  - assign source CAN node to CAN node 1
     *
     *  - initialize the source CAN node with the modified configuration
     * ==========================================================================================
     */
    IfxMultican_Can_Node_initConfig(&g_multican.canNodeConfig, &g_multican.can);

    g_multican.canNodeConfig.txPin = &IfxMultican_TXD1_P14_0_OUT;
    g_multican.canNodeConfig.rxPin = &IfxMultican_RXD1B_P14_1_IN;
    g_multican.canNodeConfig.nodeId = IfxMultican_NodeId_1;

    IfxMultican_Can_Node_init(&g_multican.canSrcNode, &g_multican.canNodeConfig);

    /* ==========================================================================================
     * Source message object configuration and initialization:
     * ==========================================================================================
     *  - load default CAN message object configuration into configuration structure
     *
     *  - define the message object ID
     *  - define the CAN message ID used during arbitration phase
     *  - define the message object as a transmit message object
     *  - enable interrupt generation in case of CAN message transmission
     *  - define interrupt node pointer to be used
     *
     *  - initialize the source CAN message object with the modified configuration
     * ==========================================================================================
     */
    IfxMultican_Can_MsgObj_initConfig(&g_multican.canMsgObjConfig, &g_multican.canSrcNode);

    g_multican.canMsgObjConfig.msgObjId = 0;
    g_multican.canMsgObjConfig.frame = IfxMultican_Frame_transmit;
    g_multican.canMsgObjConfig.txInterrupt.enabled = TRUE;
    g_multican.canMsgObjConfig.txInterrupt.srcId   = TX_INTERRUPT_SRC_ID;
    g_multican.canMsgObjConfig.control.singleDataTransfer = TRUE;
    g_multican.canMsgObjConfig.control.singleTransmitTrial = TRUE;

    IfxMultican_Can_MsgObj_init(&g_multican.canSrcMsgObj, &g_multican.canMsgObjConfig);

    /* ==========================================================================================
     * Destination message object configuration and initialization:
     * ==========================================================================================
     *  - load default CAN message object configuration into configuration structure
     *
     *  - define the message object ID (different than the ID used for source MO)
     *  - define the CAN message ID used during arbitration phase (same as ID used for source MO)
     *  - define the message object as a receive message object
     *  - enable interrupt generation in case of CAN message transmission
     *  - define interrupt node pointer to be used (different than the one used for source MO)
     *
     *  - initialize the destination CAN message object with the modified configuration
     * ==========================================================================================
     */
    IfxMultican_Can_MsgObj_initConfig(&g_multican.canMsgObjConfig, &g_multican.canSrcNode);

    g_multican.canMsgObjConfig.msgObjId = 1;
    g_multican.canMsgObjConfig.frame = IfxMultican_Frame_receive;
    g_multican.canMsgObjConfig.acceptanceMask = 0UL;
    g_multican.canMsgObjConfig.rxInterrupt.enabled = TRUE;
    g_multican.canMsgObjConfig.rxInterrupt.srcId   = RX_INTERRUPT_SRC_ID;

    IfxMultican_Can_MsgObj_init(&g_multican.canDstMsgObj, &g_multican.canMsgObjConfig);
}

/* Function to initialize both TX and RX messages with the default data values.
 * After initialization of the messages, the TX message will be transmitted.
 */
void transmitCanMessage(void)
{
    /* Define the content of the data to be transmitted */
    uint32 dataLow          = 0;
    uint32 dataHigh         = 0;
    uint32 messageID        = 0;
    static sint8 direction  = 1;
    static uint64 data      = 0x0000000000000011;

    if(IfxPort_getPinState(BUTTON) == 0)
    {
        IfxPort_setPinHigh(LED1);

        /* Invalidation of the RX message */
        IfxMultican_Message_init(&g_multican.rxMsg,
                                 INVALID_ID_VALUE,
                                 INVALID_DATA_VALUE,
                                 INVALID_DATA_VALUE,
                                 g_multican.canMsgObjConfig.control.messageLen);

        /* Check the profile */
        if((profile > First_Profile) && (profile < Last_Profile))
        {
            switch(profile)
            {
                case BCM:
                    messageID   = 0x222;
                    break;
                case DCU_1:
                    messageID   = 0x333;
                    break;
                case DCU_2:
                    messageID   = 0x444;
                    break;
                case DCU_3:
                    messageID   = 0x555;
                    break;
                case DCU_4:
                    messageID   = 0x666;
                    break;
                default: break;

            }

            // Detect limits
            if((data == 0x1100000000000000) && (direction == 1))
            {
                direction = -1;
            }
            else if((data == 0x0000000000000011) && (direction == -1))
            {
                direction = 1;
            }
            else
            {

            }

            // Shift data
            if(direction == 1)
            {
                data = data << 8;
            }
            else{
                data = data >> 8;
            }

            // Prepare data
            dataLow     = (uint32)(data & 0xFFFFFFFF);
            dataHigh    = (uint32)((data >> 32) & 0xFFFFFFFF);

            /* Initialization of the TX message */
            IfxMultican_Message_init(&g_multican.txMsg,
                                     messageID,
                                     dataLow,
                                     dataHigh,
                                     g_multican.canMsgObjConfig.control.messageLen);


            while( IfxMultican_Status_notSentBusy ==
                       IfxMultican_Can_MsgObj_sendMessage(&g_multican.canSrcMsgObj, &g_multican.txMsg) )
            {
            }
        }

        waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, 200));    /* Wait 200 milliseconds            */
    }
}

void initGPIO(void)
{
    /* Selection  */
    IfxPort_setPinMode(SEL0, IfxPort_Mode_inputPullUp);
    IfxPort_setPinMode(SEL1, IfxPort_Mode_inputPullUp);
    IfxPort_setPinMode(SEL2, IfxPort_Mode_inputPullUp);

    /* Switch ON the LED (low-level active) */
    IfxPort_setPinHigh(LED1);
    IfxPort_setPinHigh(LED2);

    /* Initialization of the LED used in this example */
    IfxPort_setPinModeOutput(LED1, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinModeOutput(LED2, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);

    /* Set the pad driver mode for both pins connected to the LEDs */
    IfxPort_setPinPadDriver(LED1, IfxPort_PadDriver_cmosAutomotiveSpeed1);
    IfxPort_setPinPadDriver(LED2, IfxPort_PadDriver_cmosAutomotiveSpeed1);

    /* Profile */
    profile = 0x00 + (!IfxPort_getPinState(SEL0)) + ((!IfxPort_getPinState(SEL1)) << 1) + ((!IfxPort_getPinState(SEL2)) << 2);

    /* Set the pad input for Button */
    IfxPort_setPinMode(BUTTON, IfxPort_Mode_inputPullUp);
}


